[tool.poetry]
name = "email-vault-backend"
version = "0.1.0"
description = ""
authors = ["Your Name nabeekh@gmail.com"]
readme = "README.md"<nabeekh@gmail.com>

[tool.poetry.dependencies]
python = "^3.12"
Flask = "^3.0.3"
python-dotenv = "1.0.0"
rococo = "^1.0.23"
Flask-Bcrypt = "cryptography"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
